// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxKJX1yrHlZ78RpHUkZpOHHIzJoN8belw',
    appId: '1:147953624032:web:2aa803dc8d98a652914185',
    messagingSenderId: '147953624032',
    projectId: 'web-scrapper-c9fe2',
    authDomain: 'web-scrapper-c9fe2.firebaseapp.com',
    databaseURL: 'https://web-scrapper-c9fe2-default-rtdb.firebaseio.com',
    storageBucket: 'web-scrapper-c9fe2.firebasestorage.app',
    measurementId: 'G-Z3G8LT88X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0VMChnPORBFVSxcpHVbVRkgVK8tyL1w',
    appId: '1:147953624032:android:1e630c06223c0d6a914185',
    messagingSenderId: '147953624032',
    projectId: 'web-scrapper-c9fe2',
    databaseURL: 'https://web-scrapper-c9fe2-default-rtdb.firebaseio.com',
    storageBucket: 'web-scrapper-c9fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtdT3RZzOcSgaOPNwj24CMvmIeyvJd22Q',
    appId: '1:147953624032:ios:fd673219d3b1ad3f914185',
    messagingSenderId: '147953624032',
    projectId: 'web-scrapper-c9fe2',
    databaseURL: 'https://web-scrapper-c9fe2-default-rtdb.firebaseio.com',
    storageBucket: 'web-scrapper-c9fe2.firebasestorage.app',
    iosBundleId: 'com.example.priceScrapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtdT3RZzOcSgaOPNwj24CMvmIeyvJd22Q',
    appId: '1:147953624032:ios:fd673219d3b1ad3f914185',
    messagingSenderId: '147953624032',
    projectId: 'web-scrapper-c9fe2',
    databaseURL: 'https://web-scrapper-c9fe2-default-rtdb.firebaseio.com',
    storageBucket: 'web-scrapper-c9fe2.firebasestorage.app',
    iosBundleId: 'com.example.priceScrapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxKJX1yrHlZ78RpHUkZpOHHIzJoN8belw',
    appId: '1:147953624032:web:32000da84644968e914185',
    messagingSenderId: '147953624032',
    projectId: 'web-scrapper-c9fe2',
    authDomain: 'web-scrapper-c9fe2.firebaseapp.com',
    databaseURL: 'https://web-scrapper-c9fe2-default-rtdb.firebaseio.com',
    storageBucket: 'web-scrapper-c9fe2.firebasestorage.app',
    measurementId: 'G-VCJ57DWRGT',
  );
}
